# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Loader
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
neo_version_range=[21.1,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod
mod_id=ten4ext
mod_name=TEN4 Extension
mod_license=GPL-3.0-only
mod_version=1.1.0
mod_group_id=com.ten4ext
mod_authors=Zkev1
mod_description=An addon for Technical Engineering 4: fixes duct hitboxes, the Liquid Unit dupe, the device IO GUI and more; adds augments, titanium ducts, new machines, JEI energy info and recipes for other mods.

# Dependencies
ten4_version=26.1.9
ten4_version_range=[26.1.9,)
jei_version=19.22.1.316
